name: CI for Java Invoice
on: [ push ]
jobs:
  linter-checks:
    name: linter tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: checkstyle check
        run: mvn checkstyle:check
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 8, 13, 15 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          #          java-version: '15'
          java-version: ${{ matrix.node }}
          distribution: 'adopt'
      - name: Test
        run: mvn test